default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hashop_development

test:
  <<: *default
  database: hashop_test

production:
  <<: *default
  database: hashop_production
  username: hashop
  password: <%= ENV['HASHOP_DATABASE_PASSWORD'] %>
